vich_uploader:
    db_driver: orm
    mappings:
        RH_image:
            uri_prefix: /images/RH
            upload_destination: '%kernel.project_dir%/public/images/RH'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
